const LANGUAGE_KEY = 'edupace-language';
const DEFAULT_LANGUAGE = 'en';

function normalizeLanguage(language) {
    return language === 'nl' ? 'nl' : DEFAULT_LANGUAGE;
}

const TRANSLATIONS = {
    en: {
        'controls.settings': 'Open settings',
        'controls.theme': 'Toggle theme',
        'controls.language': 'Toggle language',
        'nav.home': 'Dashboard',
        'nav.training': 'Training',
        'nav.logs': 'Session Log',
        'nav.instructions': 'Instructions',
        'connection.title': 'Device connection',
        'connection.help': 'Plug in EduPace to pair via USB.',
        'connection.status': 'Device',
        'connection.disconnected': 'Disconnected',
        'connection.button': 'CONNECT',
        'connection.button.connect': 'CONNECT',
        'connection.button.disconnect': 'DISCONNECT',
        'connection.button.connecting': 'CONNECTING…',
        'connection.button.reconnecting': 'RECONNECTING…',
        'connection.status.connected': 'Connected',
        'connection.status.disconnected': 'Disconnected',
        'connection.status.connecting': 'Connecting…',
        'connection.status.reconnecting': 'Reconnecting…',
        'connection.status.virtual': 'Virtual',
        'connection.status.unsupported': 'Unsupported browser',
        'connection.status.unavailable': 'Unable to list serial ports.',
        'connection.status.noDevices': 'No EduPace devices detected. Connect the console and press Scan to request access.',
        'connection.status.noSerial': 'This browser does not support serial devices.',
        'connection.status.unsupportedHint': 'This browser does not support connection with the EduPace device. Please use Chrome, Edge, or another browser that supports the Web Serial API.',
        'connection.status.unsupportedDismiss': 'Dismiss unsupported browser notice',
        'connection.devices': 'Devices',
        'connection.choose': 'Select device',
        'connection.subtitle': 'USB devices nearby',
        'connection.empty': 'No devices found. Plug in EduPace and scan again.',
        'connection.refresh': 'Refresh',
        'connection.scan': 'Scan',
        'connection.support': 'EduPace App, Chrome, or Edge recommended',
        'home.title': 'Dashboard',
        'home.subtitle': 'Temporary External Pacemaker Trainer',
        'home.searchLabel': 'Search scenarios',
        'home.searchPlaceholder': 'Search scenarios…',
        'home.quickStart.label': 'Quick start',
        'home.quickStart.title': 'Start training',
        'home.quickStart.body': 'Open the training workspace and load a scenario.',
        'home.quickStart.open': 'Open training →',
        'home.quickStart.instructions': 'Instructions',
        'home.quickStart.meta': 'Designed for CCU / ER nurse training',
        'home.scenarios.label': 'Scenarios',
        'home.scenarios.title': 'Browse',
        'home.scenarios.hint': 'Selecting a scenario opens the training workspace with that case loaded.',
        'home.scenarios.empty': 'No scenarios available yet.',
        'home.scenarios.error': 'Unable to load scenarios.',
        'home.recent.title': 'Recent',
        'home.recent.unknownTime': 'Unknown time',
        'home.recent.empty': 'No recent sessions yet.',
        'home.leaderboard.label': 'Leaderboard',
        'home.leaderboard.title': 'Top session leaders',
        'home.leaderboard.empty': 'Complete a session to populate the leaderboard.',
        'home.leaderboard.sessions': '{count} sessions',
        'home.leaderboard.noTime': 'No stabilization times yet.',
        'home.leaderboard.anonymous': 'Unnamed clinician',
        'home.leaderboard.totalLabel': 'Total sessions completed',
        'home.leaderboard.podiumTitle': 'Top training sessions',
        'home.leaderboard.stabilizationTitle': 'Top stabilization times',
        'home.leaderboard.noEntries': 'No sessions yet',
        'home.progress.title': 'My progress',
        'home.progress.selectorLabel': 'Select your name',
        'home.progress.noOperators': 'No names yet',
        'home.progress.anonymous': 'Unnamed clinician',
        'home.steps.title': 'Session steps',
        'home.steps.tag': '4 steps',
        'home.resources.label': 'Resources',
        'home.resources.title': 'Training resources',
        'home.resources.body': 'Shortcuts to manuals and instructions.',
        'home.progress.count': '{completed} / {total} scenarios stabilized',
        'home.progress.loading': 'Loading scenarios…',
        'home.progress.startHint': 'Stabilize a patient to see your progress fill up.',
        'home.progress.remaining': '{remaining} to go for full stabilization coverage.',
        'home.suggested.label': 'Suggested',
        'home.suggested.title': 'Try next',
        'home.suggested.empty': 'Add scenarios to see suggestions here.',
        'home.suggested.fallbackSummary': 'Practice this case next.',
        'home.suggested.start': 'Start training',
        'home.suggested.shuffle': 'Shuffle',
        'training.header.tag': 'Hands-on practice',
        'training.header.title': 'Training workspace',
        'training.scenario.pill': 'Scenario',
        'training.scenario.empty': 'No scenario active',
        'training.scenario.hint': 'Pick a scenario to begin training.',
        'training.scenario.start': 'Start',
        'training.scenario.end': 'End',
        'training.scenario.status': 'Select a scenario to begin.',
        'training.telemetry.noAlarms': 'No active alarms',
        'training.telemetry.calibration': 'Calibration',
        'training.telemetry.ms': 'ms',
        'training.telemetry.idle': 'Press Start to begin ECG',
        'training.learning.objective': 'Current Objective',
        'training.learning.feedback': 'Feedback',
        'training.controls.eyebrow': 'Control',
        'training.controls.input.title': 'Input source',
        'training.controls.input.hardware': 'Hardware',
        'training.controls.input.virtual': 'Virtual',
        'training.controls.input.caption': 'Choose whether the simulator follows the physical EduPace device or on-screen controls.',
        'training.pacemaker.eyebrow': 'Pacemaker',
        'training.pacemaker.parameters': 'Pacemaker parameters',
        'training.pacemaker.virtualController': 'Virtual Pacemaker Controller',
        'training.intrinsic.title': 'Intrinsic HR Settings',
        'training.menu.module': 'Module Training',
        'training.menu.clinical': 'Scenarios',
        'training.menu.trainingModes': 'Training modes',
        'training.menu.empty': 'No scenarios available',
        'training.menu.comingSoon': 'Coming soon',
        'logs.header.label': 'Recorded sessions',
        'logs.header.title': 'Session log',
        'logs.header.copy': 'Download completed runs as JSON or CSV.',
        'logs.leaderboard.label': 'Leaderboard',
        'logs.leaderboard.title': 'Scenario leaderboard',
        'logs.leaderboard.scenario': 'Scenario: {scenario}',
        'logs.leaderboard.noScenario': 'Select a session to see leaderboard stats.',
        'logs.leaderboard.rank': '#',
        'logs.leaderboard.name': 'Name',
        'logs.leaderboard.bestTime': 'Best stabilization',
        'logs.leaderboard.sessionCount': 'Sessions',
        'logs.leaderboard.sessions': '{count} sessions',
        'logs.leaderboard.empty': 'No leaderboard data yet.',
        'logs.leaderboard.anonymous': 'Unnamed clinician',
        'logs.leaderboard.noTime': '—',
        'logs.leaderboard.podiumTitle': 'Top stabilization times',
        'logs.filters.search': 'Search',
        'logs.filters.searchPlaceholder': 'Scenario, operator, notes',
        'logs.filters.sort': 'Sort by',
        'logs.filters.newest': 'Newest first',
        'logs.filters.oldest': 'Oldest first',
        'logs.filters.duration': 'Longest duration',
        'logs.empty': 'No sessions have been logged yet. Complete a run to see it here.',
        'logs.location.browserOnly': 'Browser storage (local only)',
        'logs.location.nativeHint': 'Logs are kept as a JSON file you can browse on disk.',
        'logs.location.browserHint': 'Logs stay in this browser storage unless you export them.',
        'logs.time.unknown': 'Unknown time',
        'logs.meta.notProvided': 'Not provided',
        'logs.meta.editHint': 'Double-click to edit',
        'logs.card.meta': '{date} • {duration} • {stabilization}',
        'logs.card.stabilization': 'Stabilized in {time}',
        'logs.card.stabilization.none': 'Not stabilized',
        'logs.card.addLabel': 'Add label or operator',
        'logs.detail.empty': 'Select a session to view its details.',
        'logs.detail.close': 'Close session details',
        'logs.detail.sessionId': 'Session ID',
        'logs.detail.started': 'Started',
        'logs.detail.duration': 'Duration',
        'logs.detail.stabilized': 'Stabilized',
        'logs.detail.stabilizedYes': 'Yes',
        'logs.detail.stabilizedNo': 'No',
        'logs.detail.stabilizationTime': 'Time to stabilize',
        'logs.actions.downloadJson': 'Download JSON',
        'logs.actions.downloadCsv': 'Download CSV',
        'logs.actions.delete': 'Delete entry',
        'logs.actions.deleteSelected': 'Delete selected',
        'logs.actions.deleteSelectedConfirm': 'Delete {count} selected sessions?',
        'logs.actions.deleteOperator': 'Delete operator sessions',
        'logs.actions.deleteOperatorConfirm': 'Delete all sessions for {name}?',
        'logs.actions.selectAll': 'Select all',
        'logs.actions.clearSelection': 'Clear selection',
        'logs.actions.selectSession': 'Select session',
        'logs.actions.save': 'Save',
        'logs.actions.cancel': 'Cancel',
        'logs.actions.edit': 'Edit',
        'logs.actions.review': 'View review',
        'logs.selection.count': '{count} selected',
        'logs.list.empty': 'No sessions match the current filters yet.',
        'logs.unknownScenario': 'Unknown scenario',
        'logs.form.label': 'Label',
        'logs.form.labelPlaceholder': 'e.g., Weekly practice',
        'logs.form.operator': 'Operator',
        'logs.form.operatorPlaceholder': 'Name of person running the session',
        'logs.form.notes': 'Notes / annotations',
        'logs.form.notesPlaceholder': 'Observations, alarms, adjustments, etc.',
        'logs.form.notesShort': 'Notes',
        'review.eyebrow': 'Session review',
        'review.title': 'Session review',
        'review.status.stable': 'Patient stabilized',
        'review.status.unstable': 'Patient not stabilized',
        'review.status.unknown': 'Stability unknown',
        'review.stabilizedLabel': 'Stabilized',
        'review.stabilized.yes': 'Yes',
        'review.stabilized.no': 'No',
        'review.timeLabel': 'Time to stabilize',
        'review.timeUnknown': '—',
        'review.nameLabel': 'Your name (optional)',
        'review.namePlaceholder': 'Enter your name',
        'review.nameHint': 'Start typing to see past names.',
        'review.saveClose': 'Save & Close',
        'review.close': 'Close',
        'instructions.label': 'Quick start',
        'instructions.title': 'Ready, connect, pace',
        'instructions.tagline': 'Learn how to use EduPace in simple steps',
        'instructions.manual': 'Open user manual (PDF)',
        'instructions.cta.training': 'Go to training',
        'instructions.steps.connect.step': 'Set up',
        'instructions.steps.connect.title': 'Connect the device',
        'instructions.steps.connect.body': 'Open the EduPace desktop app, plug the EduPace device into the right-most USB-C port (screen and knobs facing up), and select "CONNECT" on the Training page. Use Chrome, Edge, or another WebSerial-compatible browser.',
        'instructions.steps.input.step': 'Mode',
        'instructions.steps.input.title': 'Choose input mode',
        'instructions.steps.input.body': 'Choose Hardware to control the EduPace device, or Virtual to practice with keyboard/mouse.',
        'instructions.steps.scenario.step': 'Scenario',
        'instructions.steps.scenario.title': 'Select a scenario',
        'instructions.steps.scenario.body': 'Pick a training case from the scenario list and review the summary.',
        'instructions.steps.parameters.step': 'Tune',
        'instructions.steps.parameters.title': 'Adjust pacing parameters',
        'instructions.steps.parameters.body': 'Set RATE, OUTPUT, and SENSE with the knobs or sliders. Watch the ECG, LEDs, and HR tile.',
        'instructions.steps.review.step': 'Review',
        'instructions.steps.review.title': 'End and save',
        'instructions.steps.review.body': 'End the session, add your name and notes, and save the log.',
        'instructions.steps.settings.step': 'Customize',
        'instructions.steps.settings.title': 'Settings and stats',
        'instructions.steps.settings.body': 'Use Settings for language, light/dark mode, ECG, and sound. Review Session Log and Leaderboards to track progress.',

        'session.status.ready': 'Ready to start session.',
        'session.status.selectScenario': 'Select a scenario to begin.',
        'session.status.running': 'Session running.',
        'session.status.paused': 'Session paused.',
        'session.status.ended': 'Session ended.',
        'session.status.endedNavigation': 'Session ended when leaving training.',
        'session.controls.start': 'Start',
        'session.controls.pause': 'Pause',
        'session.controls.resume': 'Resume',

        'settings.header.label': 'Settings',
        'settings.header.title': 'Settings',
        'settings.header.reset': 'Reset to defaults',
        'settings.tabs.ecg': 'ECG',
        'settings.tabs.sound': 'Sound',
        'settings.tabs.simulation': 'Simulation',
        'settings.tabs.logs': 'Session logs',
        'settings.section.layout': 'Layout',
        'settings.section.appearance': 'Appearance',
        'settings.section.annotations': 'Annotations',
        'settings.section.beats': 'Beats',
        'settings.section.volume': 'Volume',
        'settings.section.device': 'Device behaviour',
        'settings.section.intrinsicRates': 'Scenario intrinsic rates',
        'settings.section.sessionLog': 'Session log',
        'settings.intrinsicScenario.hint': 'Set baseline intrinsic bpm for this scenario.',
        'settings.intrinsicScenario.rateLabel': 'Intrinsic rate (bpm)',
        'settings.intrinsicScenario.nsr.title': 'Normal Sinus Rhythm',
        'settings.intrinsicScenario.av3.title': 'Third-degree AV block',
        'settings.intrinsicScenario.mobitz2.title': 'Second-degree AV block (Mobitz II)',
        'settings.intrinsicScenario.slowConduction.title': 'Slow Conduction',
        'settings.intrinsicRate.title': 'Intrinsic heart rate',
        'settings.intrinsicRate.hint': 'Set baseline intrinsic bpm.',
        'settings.intrinsicRegularity.title': 'Intrinsic regularity',
        'settings.intrinsicRegularity.hint': 'Regular or irregular intrinsic rhythm.',
        'settings.intrinsicRegularity.aria': 'Intrinsic regularity',
        'settings.intrinsicRegularity.regular': 'Regular',
        'settings.intrinsicRegularity.irregular': 'Irregular',
        'settings.traceLook.title': 'Trace look',
        'settings.traceLook.hint': 'Color and stroke weight.',
        'settings.traceColor.aria': 'Trace color',
        'settings.colors.green': 'Green',
        'settings.colors.blue': 'Blue',
        'settings.colors.amber': 'Amber',
        'settings.colors.white': 'White',
        'settings.traceThickness.aria': 'Trace thickness',
        'settings.traceThickness.thin': 'Thin',
        'settings.traceThickness.normal': 'Normal',
        'settings.traceThickness.thick': 'Thick',
        'settings.gridlines.title': 'Gridlines',
        'settings.gridlines.hint': 'Toggle ECG grid overlay.',
        'settings.gridDensity.title': 'Grid density',
        'settings.gridDensity.hint': '1 mm or 2 mm boxes.',
        'settings.gridDensity.aria': 'Grid density',
        'settings.gridIntensity.title': 'Grid intensity',
        'settings.gridIntensity.hint': 'Adjust line brightness.',
        'settings.hrDisplay.title': 'HR display',
        'settings.hrDisplay.hint': 'Show heart rate overlay.',
        'settings.hrDisplay.aria': 'Heart rate color',
        'settings.leadLabel.title': 'Lead label',
        'settings.leadLabel.hint': 'Show current lead overlay.',
        'settings.leadLabel.aria': 'Lead label color',
        'settings.overlaySize.title': 'Overlay size',
        'settings.overlaySize.hint': 'Increase or reduce ECG label text.',
        'settings.overlaySize.aria': 'Overlay size',
        'settings.overlaySize.compact': 'Compact',
        'settings.overlaySize.normal': 'Normal',
        'settings.overlaySize.large': 'Large',
        'settings.sensitivityGuide.title': 'Sensitivity guide',
        'settings.sensitivityGuide.hint': 'Show current sensing threshold line.',
        'settings.paceMarkers.title': 'Pace markers',
        'settings.paceMarkers.hint': 'Show paced beat indicators.',
        'settings.paceMarkers.aria': 'Pace marker color',
        'settings.senseMarkers.title': 'Sense markers',
        'settings.senseMarkers.hint': 'Show intrinsic beat indicators.',
        'settings.senseMarkers.aria': 'Sense marker color',
        'settings.intervalRulers.title': 'Interval rulers',
        'settings.intervalRulers.hint': 'RR/PP calipers on drag.',
        'settings.qrsBeep.title': 'ECG beep',
        'settings.qrsBeep.hint': 'On or off.',
        'settings.qrsBeep.aria': 'ECG beep',
        'settings.qrsBeepVolume.title': 'ECG beep volume',
        'settings.qrsBeepVolume.hint': 'Adjust the ECG beep loudness.',
        'settings.autoLock.title': 'Auto-lock knobs',
        'settings.autoLock.hint': 'Lock after inactivity.',
        'settings.autoLock.aria': 'Auto-lock knobs',
        'settings.dateFormat.title': 'Date format',
        'settings.dateFormat.hint': 'Choose how dates display in session logs.',
        'settings.shared.format': 'Format',
        'settings.timeFormat.title': 'Time format',
        'settings.timeFormat.hint': 'Control the clock style in logs.',
        'settings.timeFormat.twentyFour': '24-hour',
        'settings.timeFormat.twelve': '12-hour',
        'settings.logStorage.title': 'Log storage',
        'settings.logStorage.hint': 'Choose or open the folder where EduPace saves session logs.',
        'settings.logStorage.detecting': 'Detecting log folder…',
        'settings.logStorage.change': 'Change location',
        'settings.logStorage.open': 'Open folder',
        'settings.logStorage.refresh': 'Refresh from disk',
        'settings.logReset.title': 'Clear session logs',
        'settings.logReset.hint': 'Delete all saved session logs and operator names.',
        'settings.logReset.action': 'Delete logs',
        'settings.logReset.confirm': 'Delete all session logs and saved people?',
        'settings.actions.save': 'Save',
        'settings.actions.saveAria': 'Save and close settings',
        'settings.shared.off': 'Off',
        'settings.shared.on': 'On'
    },
    nl: {
        'controls.settings': 'Open instellingen',
        'controls.theme': 'Schakel thema',
        'controls.language': 'Wissel taal',
        'nav.home': 'Dashboard',
        'nav.training': 'Training',
        'nav.logs': 'Sessielog',
        'nav.instructions': 'Instructies',
        'connection.title': 'Apparaatverbinding',
        'connection.help': 'Sluit EduPace via USB aan.',
        'connection.status': 'Apparaat',
        'connection.disconnected': 'Niet verbonden',
        'connection.button': 'VERBINDEN',
        'connection.button.connect': 'VERBINDEN',
        'connection.button.disconnect': 'VERBINDING VERBREKEN',
        'connection.button.connecting': 'Bezig met verbinden…',
        'connection.button.reconnecting': 'Opnieuw verbinden…',
        'connection.status.connected': 'Verbonden',
        'connection.status.disconnected': 'Niet verbonden',
        'connection.status.connecting': 'Bezig met verbinden…',
        'connection.status.reconnecting': 'Opnieuw verbinden…',
        'connection.status.virtual': 'Virtueel',
        'connection.status.unsupported': 'Browser niet ondersteund',
        'connection.status.unavailable': 'Seriële poorten kunnen niet worden geladen.',
        'connection.status.noDevices': 'Geen EduPace-apparaten gevonden. Sluit de console aan en klik op Scannen om toegang te vragen.',
        'connection.status.noSerial': 'Deze browser ondersteunt geen seriële apparaten.',
        'connection.status.unsupportedHint': 'Deze browser ondersteunt geen verbinding met het EduPace-apparaat. Gebruik Chrome, Edge of een andere browser met ondersteuning voor de Web Serial API.',
        'connection.status.unsupportedDismiss': 'Melding over niet-ondersteunde browser sluiten',
        'connection.devices': 'Apparaten',
        'connection.choose': 'Selecteer apparaat',
        'connection.subtitle': 'USB-apparaten in de buurt',
        'connection.empty': 'Geen apparaten gevonden. Sluit EduPace aan en scan opnieuw.',
        'connection.refresh': 'Vernieuwen',
        'connection.scan': 'Scannen',
        'connection.support': 'EduPace App, Chrome of Edge aanbevolen',
        'home.title': 'Dashboard',
        'home.subtitle': 'Tijdelijke externe pacemakertrainer',
        'home.searchLabel': 'Zoek scenario’s',
        'home.searchPlaceholder': 'Zoek scenario’s…',
        'home.quickStart.label': 'Snelstart',
        'home.quickStart.title': 'Begin met trainen',
        'home.quickStart.body': 'Open de trainingsomgeving en laad een scenario.',
        'home.quickStart.open': 'Training openen →',
        'home.quickStart.instructions': 'Instructies',
        'home.quickStart.meta': 'Ontworpen voor training van CCU/SEH-verpleegkundigen',
        'home.scenarios.label': 'Scenario’s',
        'home.scenarios.title': 'Bladeren',
        'home.scenarios.hint': 'Het kiezen van een scenario opent de trainingsomgeving met die casus.',
        'home.scenarios.empty': 'Nog geen scenario’s beschikbaar.',
        'home.scenarios.error': 'Scenario’s konden niet worden geladen.',
        'home.recent.title': 'Recent',
        'home.recent.unknownTime': 'Onbekende tijd',
        'home.recent.empty': 'Nog geen sessies.',
        'home.leaderboard.label': 'Ranglijst',
        'home.leaderboard.title': 'Beste sessieleiders',
        'home.leaderboard.empty': 'Voltooi een sessie om de ranglijst te vullen.',
        'home.leaderboard.sessions': '{count} sessies',
        'home.leaderboard.noTime': 'Nog geen stabilisatietijden.',
        'home.leaderboard.anonymous': 'Naam niet ingevuld',
        'home.leaderboard.totalLabel': 'Totaal aantal sessies',
        'home.leaderboard.podiumTitle': 'Top trainingssessies',
        'home.leaderboard.stabilizationTitle': 'Beste stabilisatietijden',
        'home.leaderboard.noEntries': 'Nog geen sessies',
        'home.progress.title': 'Mijn voortgang',
        'home.progress.selectorLabel': 'Kies je naam',
        'home.progress.noOperators': 'Nog geen namen',
        'home.progress.anonymous': 'Naam niet ingevuld',
        'home.steps.title': 'Sessiestappen',
        'home.steps.tag': '4 stappen',
        'home.resources.label': 'Bronnen',
        'home.resources.title': 'Trainingsbronnen',
        'home.resources.body': 'Snel naar handleiding en instructies.',
        'home.progress.count': '{completed} / {total} scenario’s gestabiliseerd',
        'home.progress.loading': 'Scenario’s worden geladen…',
        'home.progress.startHint': 'Stabiliseer een patiënt om je voortgang te zien.',
        'home.progress.remaining': 'Nog {remaining} te gaan voor volledige stabilisatie.',
        'home.suggested.label': 'Aanbevolen',
        'home.suggested.title': 'Probeer hierna',
        'home.suggested.empty': 'Voeg scenario’s toe om hier suggesties te zien.',
        'home.suggested.fallbackSummary': 'Oefen deze casus hierna.',
        'home.suggested.start': 'Start met trainen',
        'home.suggested.shuffle': 'Willekeurig',
        'training.header.tag': 'Praktijk',
        'training.header.title': 'Trainingsomgeving',
        'training.scenario.pill': 'Scenario',
        'training.scenario.empty': 'Geen actief scenario',
        'training.scenario.hint': 'Kies een scenario om te starten.',
        'training.scenario.start': 'Start',
        'training.scenario.end': 'Stop',
        'training.scenario.status': 'Selecteer een scenario om te beginnen.',
        'training.telemetry.noAlarms': 'Geen actieve alarmen',
        'training.telemetry.calibration': 'Calibratie',
        'training.telemetry.ms': 'ms',
        'training.telemetry.idle': 'Druk op Start om ECG te beginnen',
        'training.learning.objective': 'Huidig doel',
        'training.learning.feedback': 'Feedback',
        'training.controls.eyebrow': 'Bediening',
        'training.controls.input.title': 'Invoerbron',
        'training.controls.input.hardware': 'Hardware',
        'training.controls.input.virtual': 'Virtueel',
        'training.controls.input.caption': 'Kies of de simulator het fysieke EduPace-apparaat volgt of de bediening op het scherm.',
        'training.pacemaker.eyebrow': 'Pacemaker',
        'training.pacemaker.parameters': 'Pacemakerparameters',
        'training.pacemaker.virtualController': 'Virtuele pacemakercontroller',
        'training.intrinsic.title': 'Intrinsieke HR-instellingen',
        'training.menu.module': 'Moduletraining',
        'training.menu.clinical': 'Scenario’s',
        'training.menu.trainingModes': 'Trainingsmodi',
        'training.menu.empty': 'Geen scenario’s beschikbaar',
        'training.menu.comingSoon': 'Binnenkort beschikbaar',
        'logs.header.label': 'Opgeslagen sessies',
        'logs.header.title': 'Sessielog',
        'logs.header.copy': 'Download afgeronde sessies als JSON of CSV.',
        'logs.leaderboard.label': 'Ranglijst',
        'logs.leaderboard.title': 'Scenario-ranglijst',
        'logs.leaderboard.scenario': 'Scenario: {scenario}',
        'logs.leaderboard.noScenario': 'Selecteer een sessie om ranglijststatistieken te zien.',
        'logs.leaderboard.rank': '#',
        'logs.leaderboard.name': 'Naam',
        'logs.leaderboard.bestTime': 'Beste stabilisatie',
        'logs.leaderboard.sessionCount': 'Sessies',
        'logs.leaderboard.sessions': '{count} sessies',
        'logs.leaderboard.empty': 'Nog geen ranglijstgegevens.',
        'logs.leaderboard.anonymous': 'Naam niet ingevuld',
        'logs.leaderboard.noTime': '—',
        'logs.leaderboard.podiumTitle': 'Beste stabilisatietijden',
        'logs.filters.search': 'Zoeken',
        'logs.filters.searchPlaceholder': 'Scenario, operator, notities',
        'logs.filters.sort': 'Sorteren op',
        'logs.filters.newest': 'Nieuwste eerst',
        'logs.filters.oldest': 'Oudste eerst',
        'logs.filters.duration': 'Langste duur',
        'logs.empty': 'Er zijn nog geen sessies gelogd. Rond een run af om hem hier te zien.',
        'logs.location.browserOnly': 'Browseropslag (alleen lokaal)',
        'logs.location.nativeHint': 'Logs worden opgeslagen als een JSON-bestand dat je op schijf kunt openen.',
        'logs.location.browserHint': 'Logs blijven in deze browseropslag tenzij je ze exporteert.',
        'logs.time.unknown': 'Onbekende tijd',
        'logs.meta.notProvided': 'Niet opgegeven',
        'logs.meta.editHint': 'Dubbelklik om te bewerken',
        'logs.card.meta': '{date} • {duration} • {stabilization}',
        'logs.card.stabilization': 'Gestabiliseerd in {time}',
        'logs.card.stabilization.none': 'Niet gestabiliseerd',
        'logs.card.addLabel': 'Voeg label of operator toe',
        'logs.detail.empty': 'Selecteer een sessie om details te bekijken.',
        'logs.detail.close': 'Sluit sessiedetails',
        'logs.detail.sessionId': 'Sessienummer',
        'logs.detail.started': 'Gestart',
        'logs.detail.duration': 'Duur',
        'logs.detail.stabilized': 'Gestabiliseerd',
        'logs.detail.stabilizedYes': 'Ja',
        'logs.detail.stabilizedNo': 'Nee',
        'logs.detail.stabilizationTime': 'Tijd tot stabilisatie',
        'logs.actions.downloadJson': 'Download JSON',
        'logs.actions.downloadCsv': 'Download CSV',
        'logs.actions.delete': 'Verwijder item',
        'logs.actions.deleteSelected': 'Selectie verwijderen',
        'logs.actions.deleteSelectedConfirm': '{count} geselecteerde sessies verwijderen?',
        'logs.actions.deleteOperator': 'Sessies van operator verwijderen',
        'logs.actions.deleteOperatorConfirm': 'Alle sessies voor {name} verwijderen?',
        'logs.actions.selectAll': 'Alles selecteren',
        'logs.actions.clearSelection': 'Selectie wissen',
        'logs.actions.selectSession': 'Selecteer sessie',
        'logs.actions.save': 'Opslaan',
        'logs.actions.cancel': 'Annuleren',
        'logs.actions.edit': 'Bewerken',
        'logs.actions.review': 'Review bekijken',
        'logs.selection.count': '{count} geselecteerd',
        'logs.list.empty': 'Geen sessies passen nog bij de huidige filters.',
        'logs.unknownScenario': 'Onbekend scenario',
        'logs.form.label': 'Label',
        'logs.form.labelPlaceholder': 'bijv. Wekelijkse oefening',
        'logs.form.operator': 'Operator',
        'logs.form.operatorPlaceholder': 'Naam van de persoon die de sessie uitvoert',
        'logs.form.notes': 'Notities / opmerkingen',
        'logs.form.notesPlaceholder': 'Observaties, alarmen, aanpassingen, etc.',
        'logs.form.notesShort': 'Notities',
        'review.eyebrow': 'Sessiereview',
        'review.title': 'Sessiereview',
        'review.status.stable': 'Patiënt gestabiliseerd',
        'review.status.unstable': 'Patiënt niet gestabiliseerd',
        'review.status.unknown': 'Stabiliteit onbekend',
        'review.stabilizedLabel': 'Gestabiliseerd',
        'review.stabilized.yes': 'Ja',
        'review.stabilized.no': 'Nee',
        'review.timeLabel': 'Tijd tot stabilisatie',
        'review.timeUnknown': '—',
        'review.nameLabel': 'Jouw naam (optioneel)',
        'review.namePlaceholder': 'Voer je naam in',
        'review.nameHint': 'Begin te typen om eerdere namen te zien.',
        'review.saveClose': 'Opslaan & sluiten',
        'review.close': 'Sluiten',
        'instructions.label': 'Snelstart',
        'instructions.title': 'Klaar, verbinden, pacen',
        'instructions.tagline': 'Leer EduPace gebruiken in een paar korte stappen',
        'instructions.manual': 'Open gebruikershandleiding (PDF)',
        'instructions.cta.training': 'Ga naar training',
        'instructions.steps.connect.step': 'Voorbereiding',
        'instructions.steps.connect.title': 'Verbind het apparaat',
        'instructions.steps.connect.body': 'Open de EduPace-desktopapp, sluit het EduPace-apparaat aan via de meest rechtse USB-C-poort (scherm en knoppen omhoog) en kies "VERBINDEN" op de Trainingspagina. Gebruik Chrome, Edge of een andere WebSerial-compatibele browser.',
        'instructions.steps.input.step': 'Modus',
        'instructions.steps.input.title': 'Kies invoermodus',
        'instructions.steps.input.body': 'Kies Hardware om het EduPace-apparaat te bedienen of Virtueel om met toetsenbord/muis te oefenen.',
        'instructions.steps.scenario.step': 'Scenario',
        'instructions.steps.scenario.title': 'Selecteer een scenario',
        'instructions.steps.scenario.body': 'Kies een casus uit de scenariolijst en bekijk de samenvatting.',
        'instructions.steps.parameters.step': 'Afstemmen',
        'instructions.steps.parameters.title': 'Pas pacingparameters aan',
        'instructions.steps.parameters.body': 'Stel RATE, OUTPUT en SENSE in met de knoppen of schuifregelaars. Let op ECG, leds en het HR-vak.',
        'instructions.steps.review.step': 'Evaluatie',
        'instructions.steps.review.title': 'Beëindig en sla op',
        'instructions.steps.review.body': 'Beëindig de sessie, voeg je naam en notities toe en sla de log op.',
        'instructions.steps.settings.step': 'Aanpassen',
        'instructions.steps.settings.title': 'Instellingen en stats',
        'instructions.steps.settings.body': 'Gebruik Instellingen voor taal, lichte/donkere modus, ECG en geluid. Bekijk Sessielog en ranglijsten om voortgang te volgen.',

        'session.status.ready': 'Klaar om de sessie te starten.',
        'session.status.selectScenario': 'Selecteer een scenario om te beginnen.',
        'session.status.running': 'Sessie bezig.',
        'session.status.paused': 'Sessie gepauzeerd.',
        'session.status.ended': 'Sessie beëindigd.',
        'session.status.endedNavigation': 'Sessie beëindigd bij het verlaten van training.',
        'session.controls.start': 'Start',
        'session.controls.pause': 'Pauze',
        'session.controls.resume': 'Hervatten',

        'settings.header.label': 'Instellingen',
        'settings.header.title': 'Instellingen',
        'settings.header.reset': 'Terugzetten naar standaardwaarden',
        'settings.tabs.ecg': 'ECG',
        'settings.tabs.sound': 'Geluid',
        'settings.tabs.simulation': 'Simulatie',
        'settings.tabs.logs': 'Sessielogs',
        'settings.section.layout': 'Indeling',
        'settings.section.appearance': 'Uiterlijk',
        'settings.section.annotations': 'Annotaties',
        'settings.section.beats': 'Slagen',
        'settings.section.volume': 'Volume',
        'settings.section.device': 'Apparaatgedrag',
        'settings.section.intrinsicRates': 'Scenario intrinsieke hartslag',
        'settings.section.sessionLog': 'Sessielog',
        'settings.intrinsicScenario.hint': 'Stel de intrinsieke bpm in voor dit scenario.',
        'settings.intrinsicScenario.rateLabel': 'Intrinsieke rate (bpm)',
        'settings.intrinsicScenario.nsr.title': 'Normaal sinusritme',
        'settings.intrinsicScenario.av3.title': 'Derdegraads AV-blok',
        'settings.intrinsicScenario.mobitz2.title': 'Tweedegraads AV-blok (Mobitz II)',
        'settings.intrinsicScenario.slowConduction.title': 'Trage geleiding',
        'settings.intrinsicRate.title': 'Intrinsieke hartslag',
        'settings.intrinsicRate.hint': 'Stel de intrinsieke bpm in.',
        'settings.intrinsicRegularity.title': 'Intrinsieke regelmaat',
        'settings.intrinsicRegularity.hint': 'Regelmatig of onregelmatig intrinsiek ritme.',
        'settings.intrinsicRegularity.aria': 'Intrinsieke regelmaat',
        'settings.intrinsicRegularity.regular': 'Regelmatig',
        'settings.intrinsicRegularity.irregular': 'Onregelmatig',
        'settings.traceLook.title': 'Uitstraling van trace',
        'settings.traceLook.hint': 'Kleur en lijngewicht.',
        'settings.traceColor.aria': 'Tracekleur',
        'settings.colors.green': 'Groen',
        'settings.colors.blue': 'Blauw',
        'settings.colors.amber': 'Amber',
        'settings.colors.white': 'Wit',
        'settings.traceThickness.aria': 'Lijndikte',
        'settings.traceThickness.thin': 'Dun',
        'settings.traceThickness.normal': 'Normaal',
        'settings.traceThickness.thick': 'Dik',
        'settings.gridlines.title': 'Rasterlijnen',
        'settings.gridlines.hint': 'Schakel ECG-raster overlay.',
        'settings.gridDensity.title': 'Rasterdichtheid',
        'settings.gridDensity.hint': '1 mm- of 2 mm-vakken.',
        'settings.gridDensity.aria': 'Rasterdichtheid',
        'settings.gridIntensity.title': 'Rasterintensiteit',
        'settings.gridIntensity.hint': 'Pas lijnhelderheid aan.',
        'settings.hrDisplay.title': 'HR-weergave',
        'settings.hrDisplay.hint': 'Toon hartslagoverlay.',
        'settings.hrDisplay.aria': 'Hartslagkleur',
        'settings.leadLabel.title': 'Afleidingslabel',
        'settings.leadLabel.hint': 'Toon huidige afleiding.',
        'settings.leadLabel.aria': 'Kleur afleidingslabel',
        'settings.overlaySize.title': 'Overlaygrootte',
        'settings.overlaySize.hint': 'Vergroot of verklein ECG-labeltekst.',
        'settings.overlaySize.aria': 'Overlaygrootte',
        'settings.overlaySize.compact': 'Compact',
        'settings.overlaySize.normal': 'Normaal',
        'settings.overlaySize.large': 'Groot',
        'settings.sensitivityGuide.title': 'Sensitiviteitslijn',
        'settings.sensitivityGuide.hint': 'Toon huidige sensordrempel.',
        'settings.paceMarkers.title': 'Pace-markeringen',
        'settings.paceMarkers.hint': 'Toon pacingindicatoren.',
        'settings.paceMarkers.aria': 'Kleur pace-markering',
        'settings.senseMarkers.title': 'Sense-markeringen',
        'settings.senseMarkers.hint': 'Toon intrinsieke slagen.',
        'settings.senseMarkers.aria': 'Kleur sense-markering',
        'settings.intervalRulers.title': 'Intervalcalipers',
        'settings.intervalRulers.hint': 'RR/PP-calipers tijdens slepen.',
        'settings.qrsBeep.title': 'ECG-beep',
        'settings.qrsBeep.hint': 'Aan of uit.',
        'settings.qrsBeep.aria': 'ECG-beep',
        'settings.qrsBeepVolume.title': 'ECG-beepvolume',
        'settings.qrsBeepVolume.hint': 'Pas het volume van de ECG-beep aan.',
        'settings.autoLock.title': 'Automatisch knoppen vergrendelen',
        'settings.autoLock.hint': 'Vergrendel na inactiviteit.',
        'settings.autoLock.aria': 'Automatisch vergrendelen',
        'settings.dateFormat.title': 'Datumnotatie',
        'settings.dateFormat.hint': 'Kies hoe data in sessielogs worden getoond.',
        'settings.shared.format': 'Formaat',
        'settings.timeFormat.title': 'Tijdnotatie',
        'settings.timeFormat.hint': 'Bepaal de klokstijl in logs.',
        'settings.timeFormat.twentyFour': '24-uurs',
        'settings.timeFormat.twelve': '12-uurs',
        'settings.logStorage.title': 'Logopslag',
        'settings.logStorage.hint': 'Kies of open de map waar EduPace sessielogs bewaart.',
        'settings.logStorage.detecting': 'Logmap wordt gedetecteerd…',
        'settings.logStorage.change': 'Locatie wijzigen',
        'settings.logStorage.open': 'Map openen',
        'settings.logStorage.refresh': 'Verversen vanaf schijf',
        'settings.logReset.title': 'Sessielogs wissen',
        'settings.logReset.hint': 'Verwijder alle opgeslagen sessielogs en operatornamen.',
        'settings.logReset.action': 'Logs verwijderen',
        'settings.logReset.confirm': 'Alle sessielogs en opgeslagen namen verwijderen?',
        'settings.actions.save': 'Opslaan',
        'settings.actions.saveAria': 'Instellingen opslaan en sluiten',
        'settings.shared.off': 'Uit',
        'settings.shared.on': 'Aan'
    }
};

function getTranslation(language, key) {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS[DEFAULT_LANGUAGE]?.[key] || null;
}

function getCurrentLanguage() {
    const documentLang = document.documentElement.getAttribute('lang');
    const storedLang = localStorage.getItem(LANGUAGE_KEY);
    return normalizeLanguage(documentLang || storedLang || DEFAULT_LANGUAGE);
}

function translateKey(key, language = getCurrentLanguage()) {
    return getTranslation(language, key) ?? key;
}

function applyTranslations(language) {
    const normalizedLanguage = normalizeLanguage(language);

    document.querySelectorAll('[data-i18n-key]').forEach((element) => {
        const key = element.dataset.i18nKey;
        if (!key) return;

        const translation = getTranslation(normalizedLanguage, key);
        if (!translation) return;

        const attrTargets = (element.dataset.i18nAttr || '')
            .split(',')
            .map((attr) => attr.trim())
            .filter(Boolean);

        if (attrTargets.length) {
            attrTargets.forEach((attr) => element.setAttribute(attr, translation));
        } else {
            element.textContent = translation;
        }
    });
}

function updateLanguageButtons(language) {
    const isEnglish = language === 'en';
    const buttons = document.querySelectorAll('[data-language-toggle]');

    buttons.forEach((button) => {
        const label = button.querySelector('[data-language-label]');
        if (label) {
            label.textContent = language.toUpperCase();
        }

        button.setAttribute('aria-pressed', String(isEnglish));
        button.setAttribute('aria-label', isEnglish ? 'Switch to Dutch' : 'Switch to English');
    });
}

function applyLanguage(language) {
    const normalizedLanguage = normalizeLanguage(language);
    document.documentElement.setAttribute('lang', normalizedLanguage);
    localStorage.setItem(LANGUAGE_KEY, normalizedLanguage);
    updateLanguageButtons(normalizedLanguage);
    applyTranslations(normalizedLanguage);

    document.dispatchEvent(
        new CustomEvent('edupace:language-changed', {
            detail: { language: normalizedLanguage }
        })
    );
}

function bindLanguageToggles(toggleElements) {
    toggleElements.forEach((toggle) => {
        if (toggle.dataset.languageBound === 'true') return;

        toggle.dataset.languageBound = 'true';
        toggle.addEventListener('click', () => {
            const currentLanguage = document.documentElement.getAttribute('lang') || DEFAULT_LANGUAGE;
            const nextLanguage = currentLanguage === 'en' ? 'nl' : 'en';
            applyLanguage(nextLanguage);
        });
    });

    const currentLanguage = document.documentElement.getAttribute('lang') || DEFAULT_LANGUAGE;
    applyLanguage(currentLanguage);
}

function initLanguageToggle() {
    const savedLanguage = localStorage.getItem(LANGUAGE_KEY) || DEFAULT_LANGUAGE;
    applyLanguage(savedLanguage);

    const toggles = Array.from(document.querySelectorAll('[data-language-toggle]'));
    if (toggles.length) {
        bindLanguageToggles(toggles);
        return;
    }

    const observer = new MutationObserver(() => {
        const discovered = Array.from(document.querySelectorAll('[data-language-toggle]'));
        if (discovered.length) {
            bindLanguageToggles(discovered);
            observer.disconnect();
        }
    });

    observer.observe(document.body, { childList: true, subtree: true });
}

export { initLanguageToggle, getCurrentLanguage, translateKey, applyLanguage };
